### ISSUE TITLE
Add Google Play Services icons if they enabled for a game just like the android version

### ISSUE THREAD

**Issue by mushfiqweb** [archon810/toolbox-for-google-play-store-public#10]
#### **Suggestion**
You might add the icons of play games service if a game has play games achievements, cloud sync, leaderboard etc just like the android play store has. 
Check below screenshot of android version.

 ![2017-03-18_07h55_37](https://cloud.githubusercontent.com/assets/2777499/24068077/6a92d84e-0bb0-11e7-88da-a5e8dbec04d1.png)

The same thing might be added in somewhere in the below image, which is a web version.

![2017-03-18_07h58_37](https://cloud.githubusercontent.com/assets/2777499/24068099/ba9f4bba-0bb0-11e7-88b3-0c468ca35722.png)

**Comment by archon810** [comment]
This would depend on whether the web Play Store exposes this kind of data, which, if they're not already showing them, I doubt. Otherwise, they'd be showing them.

@corbindavenport Advise?

**Comment by corbindavenport** [comment]
Yeah, my guess would be that the web site doesn't expose this info, kind of like the end date on app sales. Still, I'll do some digging and see if I can get something working.

**Comment by corbindavenport** [comment]
So far I haven't found a way to access whatever data the Play Store application is accessing. I was hoping I would find an endpoint by searching through Play Store APKs, logcats packet sniffers, etc - but nothing has come up. I definitely want this to work at some point, I just haven't found a solution.

Closing the issue for now.
