### ISSUE TITLE
Consider using event pages instead of a persistently-running background page

### ISSUE THREAD

**Issue by ngyikp** [archon810/toolbox-for-google-play-store-public#11]
Currently, the extension uses a background page to load settings and constantly runs in the background eating RAM even if the user doesn't have any Play Store tabs open.

The quick fix is to add `"persistent": false` in `manifest.json`

https://developer.chrome.com/extensions/event_pages

A better way is to use `chrome.storage` so that a background page is never needed, though migrating old `localStorage` to the new `chrome.storage` might be a little tricky.

https://developer.chrome.com/extensions/storage

**Comment by archon810** [comment]
@corbindavenport I believe v2.0 has switched to these, right?

**Comment by corbindavenport** [comment]
Correct.
