### ISSUE TITLE
Feature_ Please Add a Link To ApkPure.com

### ISSUE THREAD

**Issue by zimo55** [archon810/toolbox-for-google-play-store-public#13]
This is the best extension i ever used, make my job easier ,thanks.
It Would more awesome if you add a link to apkpure

**Comment by archon810** [comment]
Dupe of #5.

**Comment by TroyByn** [comment]
sh
sudo tar -xvf jetbrains-toolbox-*.tar.gz -C /opt/
cd /opt/jetbrains-toolbox-*/
./jetbrains-toolbox
