### ISSUE TITLE
Stopped working (includes Images for Comparison)... 

### ISSUE THREAD

**Issue by Ibuprophen** [archon810/toolbox-for-google-play-store-public#14]
This Addon is available for the Firefox Mobile Browser and it just doesn't seem to work. 

I've provided screenshot images with them labeled accordingly that will easily reflect what it supposed to look like and what it does look like. 

I currently have the latest version of the Firefox Mobile Browser.

Thank you very much for your time and understanding! 
![expected to look like - addon settings](https://user-images.githubusercontent.com/18060271/29332149-03c989d0-81cd-11e7-9146-91cbbd1c32a3.png)
![expected to look like - play store](https://user-images.githubusercontent.com/18060271/29332164-1182753c-81cd-11e7-90fa-fc399a1788f0.png)
![currently looks like - addon settings](https://user-images.githubusercontent.com/18060271/29332179-221527c8-81cd-11e7-95d0-b59e3e4f120f.png)
![currently looks like - play store](https://user-images.githubusercontent.com/18060271/29332196-322e8d48-81cd-11e7-8c64-efe889469cd8.png)

**Comment by archon810** [comment]
@corbindavenport Is this supposed to work on Firefox Mobile yet?

**Comment by corbindavenport** [comment]
I didn't do much testing on Firefox for Android, because it's a major pain to test extensions on it (you can't load them from your local files like on the desktop). I do want to make sure it works properly though, at least with the desktop Play Store, so I'll try to get this bug resolved.

**Comment by Ibuprophen** [comment]
Thank you very much!

**Comment by Ibuprophen** [comment]
I'm just wondering @corbindavenport if there was anything new with this? 

Thank you very much! :-)

**Comment by archon810** [comment]
@corbindavenport We good to push once you fix that shadow thing?

**Comment by corbindavenport** [comment]
Yep.

**Comment by archon810** [comment]
v2.0 that fixes this is now out for Chrome and is queued up for FF and Opera.
