### ISSUE TITLE
Fails to find "Testing version" intermittently.

### ISSUE THREAD

**Issue by bikram-agarwal** [archon810/toolbox-for-google-play-store-public#17]
#### Expected behavior
When I go to any app's Play Store page, if that app has a testing / beta version, the page should show 

> A testing program for this app is available. More info

And that More info link should take me to the beta enrollment page of that app.

#### Actual behavior
Most of the time, the apps' page says 

> Testing version not available for this account.

But if I directly go to that app's beta enrollment page, by going to https://play.google.com/apps/testing/app.pkg.name , I do get the "Become a tester" button and I am able to enroll into the beta.

Alternatively, if I keep refreshing the app's Play Store page, after multiple attempts, it is finally able to detect the testing program and shows the "A testing program for this app is available."

#### Steps to reproduce the problem
Try https://play.google.com/store/apps/details?id=com.lastpass.lpandroid.beta
It shows "Testing version not available for this account." most of the time. But https://play.google.com/apps/testing/com.lastpass.lpandroid.beta gives me the "Become a tester" button and I am able to enroll into the beta.
OR
keep refreshing https://play.google.com/store/apps/details?id=com.lastpass.lpandroid.beta and after 10-15 times, it will say "A testing program for this app is available."

**Comment by archon810** [comment]
This is a bug that @corbindavenport has fixed in the version I'd been testing for the past several weeks. It also fixes the "undefined" pname for AB, AP, AM buttons too.

@corbindavenport Are we ready to release this?

**Comment by archon810** [comment]
v2.0 that fixes this is now out for Chrome and will be queued up for FF and Opera shortly.

**Comment by archon810** [comment]
FF and Chrome listings submitted for review.
