### ISSUE TITLE
Kind of loading loop with "Looking for testing program..."

### ISSUE THREAD

**Issue by evowizz** [archon810/toolbox-for-google-play-store-public#2]
#### Expected behavior
The loading should end..

#### Actual behavior
The loading thing of "_Looking for testing program..._" doesn't end

#### Steps to reproduce the problem
Go on an app web page

![image](https://cloud.githubusercontent.com/assets/9381261/20932737/fdf9e594-bbd5-11e6-8b41-2dc58d36e714.png)

**Comment by corbindavenport** [comment]
Are you logged into a Google account?

**Comment by evowizz** [comment]
Always :)

**Comment by corbindavenport** [comment]
Can you copy and paste your Chrome log? You can open it by right-clicking on the Play store page, clicking Inspect Element, and switching to the Console tab in the popup window.

**Comment by evowizz** [comment]
Here you go :) 
```
Error in event handler for (unknown): TypeError: Cannot read property 'indexOf' of undefined
    at chrome-extension://fepaalfjfchbdianlgginbmpeeacahoo/js/contentscript.js:88:69
```

**Comment by corbindavenport** [comment]
So it's an issue with the code that checks for multiple Google accounts, and checks for the beta program with whichever one you're logged into. I can't reproduce the error, but I'm working on a fix that should work.

**Comment by evowizz** [comment]
Thanks! :)

**Comment by cyberdionisio** [comment]
I think the language have something to do with this. If the variable in the url is set to "&hl=en", then the extension works, but if I turn it to "&hl=es" (my native language) it fall in a loop. Hope this helps.

**Comment by archon810** [comment]
We've pushed out a fix for this issue, which was indeed caused by a foreign language. Look for v1.0.9 in the next hour and report back please.

**Comment by cyberdionisio** [comment]
Hi, it works fine now, just some misalignment in there, but nothing serious.

![apkpls](https://cloud.githubusercontent.com/assets/24440610/21031458/5bd4ab74-bd82-11e6-8508-b3328731dfe3.png)

**Comment by archon810** [comment]
Yeah, we spotted this too. Will need to tweak some CSS. @corbindavenport?

**Comment by cyberdionisio** [comment]
Sorry, I talked too soon, When there is not a beta program, the extension did not show anything.
EDIT: Maybe some cache isue? Force a refresh and it works now...

**Comment by archon810** [comment]
Yeah... looks pretty bad, for example in French:
![](http://i.imgur.com/fpQAYm6.png)

**Comment by evowizz** [comment]
Yup 👍 :/

**Comment by cyberdionisio** [comment]
V1.0.10 works great! Thanks.

**Comment by archon810** [comment]
We've also fixed the UI issues in foreign languages. Closing.

**Comment by evowizz** [comment]
Thanks for fixing the bugs guys ;) and also thanks for this nice extension :)
