### ISSUE TITLE
APKMirror button still clickable even though it's disabled

### ISSUE THREAD

**Issue by EdricChan03** [archon810/toolbox-for-google-play-store-public#22]
#### Expected behavior
If the app listing is not available on APKMirror, the button should be disabled and when clicked, will not do anything.

#### Actual behavior
When the app listing is not available on APKMirror, the button is disabled but when clicked, it searches for the app on APKMirror.

#### Steps to reproduce the problem
1. Go to the app listing for Monument Valley [here](https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley "View Monument Valley on Google Play Store")
2. When the page finishes loading, there will be three buttons for the Appbrain, Android Police and APKMirror listing. The APKMirror button should be disabled while the others should be enabled.
3. When clicking on the APKMirror button, even if it's in a disabled state, it actually searches for the app's package name on APKMirror.
Here's a GIF for more info:
![apkmirror button](https://user-images.githubusercontent.com/20047125/34483137-8efd3324-eff7-11e7-9bd7-6c56723b3761.gif)

**Comment by corbindavenport** [comment]
This is the intended behavior. When the app isn't found on APKMirror, the extension won't check again for a few hours. Since there is a small chance that the app has been uploaded since the extension last checked, we allow users to manually check by clicking the button.
