### ISSUE TITLE
Add support for new web Play Store design

### ISSUE THREAD

**Issue by jise** [archon810/toolbox-for-google-play-store-public#23]
#### Expected behavior
Extension adds additional buttons to Google Play Store web page.

#### Actual behavior
Does nothing now :(

#### Steps to reproduce the problem
Test the extension functionality in Chrome 64 and then update to Chrome 65...

**Comment by archon810** [comment]
The recent changes to the web Play Store broke our beloved Toolbox. The developer finally got the new UI and is working on fixes, which we expect shortly.

**Comment by jise** [comment]
Thank you very much!
So this bug wasn't connected with Chrome update, but with Google Play Store web update.

**Comment by SuperSandro2000** [comment]
Google A/B is causing trouble like always.
Would the update fix that owned apps that are on sale are not displayed as owned?

**Comment by archon810** [comment]
@SuperSandro2000 I'm not sure what you mean. Do you have an example? Are we talking about the Play Store itself or Toolbox?

**Comment by SuperSandro2000** [comment]
More about play store itself.

![](https://i.imgur.com/OCStD6k.jpg)

![](https://i.imgur.com/pKQeoQU.jpg)
The pics were shot in this order.
Happens on desktop too. Quite annoying.

**Comment by jise** [comment]
It is working now again without any update for this extension.
So something was changed on Google Play Store web itself?

**Comment by SuperSandro2000** [comment]
Not for me. Probably some stupid A/B testing.

**Comment by archon810** [comment]
Yeah, the new design may be still flip flopping for people. We're almost done with the update.

**Comment by archon810** [comment]
They rolled back the design, so we're waiting to see what happens right now.

**Comment by rakleed** [comment]
So when will you fix the bug?

**Comment by archon810** [comment]
v2.2 released (for Chrome for now - Firefox, Opera when we see nothing is broken)!
