### ISSUE TITLE
Add button to view all purchased apps and upgrades.

### ISSUE THREAD

**Issue by jtitamer** [archon810/toolbox-for-google-play-store-public#26]
A button or link that will show all purchased apps on the currently logged in account.

Similar to the Android App which does this only for The Chrome browser as an extension. Here is the link to the Android app... https://play.google.com/store/apps/details?id=com.azefsw.purchasedapps

This should be possible because there is already an App for Android phones that does this. It would be better than the Android app because if you have multiple android devices you can easily choose which devices you would like to install it on from the Chrome browser Play Store site using a computer.

**Comment by archon810** [comment]
I think this is a bit out of scope for this extension. There's no obvious way to do this that I know of, and it'd require creating a whole separate page whereas the Toolbox is primarily for manipulating and tweaking existing pages.

Though if someone knows how to create a list of paid apps you own, I'll listen.

**Comment by Madis0** [comment]
OP is just looking for this: https://play.google.com/store/account/orderhistory
Maybe just add a more prominent button for it? (Found from Account > Order history otherwise.)

**Comment by archon810** [comment]
I don't think that's what OP was looking for since they were comparing an app created entirely for the purpose of listing such apps. This extension will not be doing that, and the link you referenced is found easily enough already, there really is no benefit in having the extension stuff it somewhere else.

I'll close this.
