### ISSUE TITLE
Google Play keeps spamming me with apps

### ISSUE THREAD

**Issue by jaguarjon53** [archon810/toolbox-for-google-play-store-public#27]
#### Expected behavior
Expect opting out of beta apps to stay opted out

#### Actual behavior
Opt out works for limited time but starts up again

#### Steps to reproduce the problem
Not sure how to repeat.

**Comment by jaguarjon53** [comment]
Google Play beta apps actually cut in regardless of what I'm doing, phone calls, composing SMS, emails.... Could be dangerous

**Comment by archon810** [comment]
This is not a problem with the extension. Closing.
