### ISSUE TITLE
Suggestion - Direct APK download

### ISSUE THREAD

**Issue by pewingfield** [archon810/toolbox-for-google-play-store-public#3]
I would suggest an option to directly download an APK from the Play Store itself if at all possible. Websites like APK mirror do not host everything, and so a direct option would be nice

**Comment by archon810** [comment]
Thanks, we think it'd be nice too, but we currently have no plans to offer an apk downloader.

**Comment by bugaevc** [comment]
Does Play Store even allow you to download an APK directly?

**Comment by corbindavenport** [comment]
Not officially, no.
