### ISSUE TITLE
PageAction

### ISSUE THREAD

**Issue by Madis0** [archon810/toolbox-for-google-play-store-public#32]
#### Expected behavior
The button should be a PageAction, which would make it have a dot in Chromium on affected pages (grayed out otherwise) and on Firefox/Vivaldi, make it appear in the address bar.

#### Actual behavior
It is a normal button, so it appears on all sites, including those it does not affect. Cluttering and confusing UX.

#### Steps to reproduce the problem
Install the extension in mentioned browsers, watch it's behaviour.

**Comment by archon810** [comment]
@corbindavenport Your input requested.

**Comment by corbindavenport** [comment]
This has been implemented and will be in the next release of Toolbox.

![screenshot from 2019-02-11 22-52-04](https://user-images.githubusercontent.com/3879063/52610616-e58c9300-2e4f-11e9-9d52-f04f09bc29d2.png)

**Comment by corbindavenport** [comment]
Looking into this.

**Comment by archon810** [comment]
This has been resolved in v2.5.
