### ISSUE TITLE
Bug: Better screenshot gallery option not working anymore

### ISSUE THREAD

**Issue by sillikk** [archon810/toolbox-for-google-play-store-public#34]
#### Expected behavior
The arrow buttons on Play Store screenshot galleries should be replaced with a horizontal scrollbar.

#### Actual behavior
Default arrow are there and scrolling with keys is not possible

#### Steps to reproduce the problem
Visit an app page. It worked in the past but just stopped working a few weeks/months ago.

**Comment by archon810** [comment]
Hi,

We're aware of the issue and are testing a fix right now. Hopefully, we'll be able to push it out in the next few days.

**Comment by corbindavenport** [comment]
The Play Store changed its HTML code a while back, which broke some Toolbox features. Version 2.5 with the required fixes is nearly complete.

**Comment by sillikk** [comment]
Great!

Le mer. 3 avr. 2019 à 17:30, Corbin Davenport <notifications@github.com> a
écrit :

**Comment by archon810** [comment]
The fix has been released (already available in Chrome and pending for the other platforms).
