### ISSUE TITLE
"Toolbox for Google Play" extension breaks wishlist button

### ISSUE THREAD

**Issue by archon810** [archon810/toolbox-for-google-play-store-public#37]
Reported via email.

> FYI, the current version of "Toolbox for Google Play Store" hides (or otherwise breaks) the "Add to Wishlist" button that would normally be visible in the same spot. So as long as this extension is enabled, I can't add any apps to my wishlist.
>
> Enjoy.

**Comment by archon810** [comment]
With extension:
![image](https://user-images.githubusercontent.com/469543/64054144-8e73b480-cb3a-11e9-8480-d14f9fb53b8f.png)


Without:
![image](https://user-images.githubusercontent.com/469543/64054150-94699580-cb3a-11e9-982b-4914e8866b3b.png)

**Comment by pdkpv** [comment]
I confirm the problem exists

![2019-09-04_18-58-32](https://user-images.githubusercontent.com/43634070/64271595-4099ea80-cf46-11e9-9b75-e1f8d0c3b414.jpg)

**Comment by archon810** [comment]
We have a fix in the works, hoping to roll it out this week.

**Comment by archon810** [comment]
Fixed in v2.6, rolling out now.
