### ISSUE TITLE
The extension is broken

### ISSUE THREAD

**Issue by pdkpv** [archon810/toolbox-for-google-play-store-public#41]
APKMirror button is always in the "Loading ..." status.
Beta program button - not displayed.

Google Chrome 89.0.4389.90
Toolbox v2.7.1

![2021-03-15_18-19-36](https://user-images.githubusercontent.com/43634070/111177257-1b664d80-85bb-11eb-9b82-7f9767ba2722.jpg)
![2021-03-15_18-15-27](https://user-images.githubusercontent.com/43634070/111177270-1ef9d480-85bb-11eb-8b5b-86820fa513d0.jpg)

**Comment by archon810** [comment]
Hmm, that is odd. I can't reproduce this and all the buttons have been working as expected for a while, including in Chrome 89.

If you open the extension in the list of extensions in Chrome (chrome://extensions/?id=fepaalfjfchbdianlgginbmpeeacahoo), then go to Inspect views and click on "background page," and then browse some Play Store listings, do you see anything in the Console output? You should be seeing something like this:

![image](https://user-images.githubusercontent.com/469543/111202284-ec32ea80-8580-11eb-81f9-f7092a8f9e3e.png)

As well as some API requests:
![image](https://user-images.githubusercontent.com/469543/111202337-fa810680-8580-11eb-8a4f-fccb639d3d6b.png)

**Comment by pdkpv** [comment]
@archon810 

I found the reason for the crash: AdGuard for Windows is breaking the extension. Later I will try to figure out which of the filters or settings is directly related to the breakdown. And I will write here about it.

**Comment by TPS** [comment]
> I found the reason for the crash: AdGuard for Windows is breaking the extension. Later I will try to figure out which of the filters or settings is directly related to the breakdown. And I will write here about it.

@ameshkov Do you wish to triage?

**Comment by ameshkov** [comment]
@TPS @pdkpv can't reproduce with the default settings and filter lists. Maybe some custom filter list is responsible?

**Comment by pdkpv** [comment]
@ameshkov @TPS

The reason is this setting :)

![2021-03-17_15-15-54](https://user-images.githubusercontent.com/43634070/111465987-c3068b80-8733-11eb-94d7-50af04421225.jpg)

@archon810 Apparently issues can be closed.
