### ISSUE TITLE
Two language selection appear

### ISSUE THREAD

**Issue by maxelo** [archon810/toolbox-for-google-play-store-public#42]
#### Expected behavior
There should be just one bar to change language on the Toolbox for google play extension

#### Actual behavior
Now I have two bars to change language

#### Steps to reproduce the problem
This seems to appear wherever I acces to an app description on google play
![Portapapeles01](https://user-images.githubusercontent.com/1003307/146048649-12aadb0e-44aa-4e96-9527-0f430d587d59.jpg)

**Comment by archon810** [comment]
Thanks for reporting. This is a known issue (because Google's current Play Store site is buggy) and isn't a problem in the upcoming redesign. Nevertheless, we have a fix, which I'll try to push out shortly.

**Comment by maxelo** [comment]
thanks for your work! =)

**Comment by archon810** [comment]
Looks like the fix isn't working properly, so I sent it back to the kitchen.
![image](https://user-images.githubusercontent.com/469543/148620328-c0cfdee4-91f8-493d-bc5a-7123817aadd8.png)

**Comment by archon810** [comment]
The fix is included in the latest version of the extension v2.9.
