### ISSUE TITLE
Need extension optimization for new Google Play design

### ISSUE THREAD

**Issue by pdkpv** [archon810/toolbox-for-google-play-store-public#48]
In the new design of Google Play, the extension buttons are not optimized and break the display of elements.

![image](https://user-images.githubusercontent.com/43634070/171385721-1d45272d-5803-4ff8-a9ca-1026f50a3d21.png)

**Comment by archon810** [comment]
We're aware of the visual issues and will release an update soon with the fix. Thanks for reporting.

**Comment by pdkpv** [comment]
@archon810

Is the update out yet?

**Comment by archon810** [comment]
@pdkpv Unfortunately, no. The primary developer isn't able to maintain the extension anymore, and this issue wasn't fixed. I'll need to find someone else to take over.

**Comment by DagimBirhanu7** [comment]
ok

**Comment by archon810** [comment]
This update has been released in v3.0.
