### ISSUE TITLE
Adding Arabic and Persian languages to the language picker

### ISSUE THREAD

**Issue by siavashi** [archon810/toolbox-for-google-play-store-public#51]
#### Expected behavior
Arabic is the 4th language in the world in terms of the population of its native speakers. and deserves recognition.
#### Actual behavior
Can't select Arabic or Persian Language

**Comment by archon810** [comment]
Indeed, looks like our language list is not complete. I'll look into expanding it. Now to find the full list of languages supported by the Play Store...

**Comment by archon810** [comment]
We currently use https://support.google.com/googleplay/android-developer/table/4419860?hl=en, but that's for the Play Console rather than the Play Store's interface, so it doesn't seem to be the right list.

**Comment by archon810** [comment]
There's a list here, but unclear what its source is https://www.ibabbleon.com/Google-Play-Store-Language-Codes.html.

**Comment by archon810** [comment]
Looks like Arabic [wasn't supported before](https://stackoverflow.com/questions/29532407/how-can-i-switch-my-google-play-language-to-arabic), but is now. For example: https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically&hl=ar.

![image](https://user-images.githubusercontent.com/469543/185251693-2635128e-7d1e-4f31-b08c-9e719b9b543f.png)

**Comment by archon810** [comment]
I've added Arabic. This change will go live with the next release (which doesn't have a date right now).
![image](https://user-images.githubusercontent.com/469543/185251857-71b94a74-a385-4b8a-aa4a-12752edcaa80.png)
