### ISSUE TITLE
Feature - Add language dropdown menu

### ISSUE THREAD

**Issue by jise** [archon810/toolbox-for-google-play-store-public#6]
I use every day many times this manual trick for switching reviews language by adding &hl=[language] to an app url for example:
https://play.google.com/store/apps/details?id=com.google.android.webview
=>
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=cs
or
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

There was built-in dropdown menu for changing language and currency in Google Play before 2013, but this dropdown menu has been removed unfortunately after GP redesign.

PS: Thank you very much for Toolbox for Google Play Store™!

**Comment by archon810** [comment]
This is a good suggestion. Any idea where we can get a definitive list of all languages?

**Comment by archon810** [comment]
Looks like this is a good place: https://support.google.com/googleplay/android-developer/table/4419860?hl=en.

**Comment by archon810** [comment]
This was released at some point in the past.
