### ISSUE TITLE
First item in context menu of "Toolbox for Google Play Store™" doesn't work as expected

### ISSUE THREAD

**Issue by jise** [archon810/toolbox-for-google-play-store-public#7]
#### Expected behavior
Should open Toolbox for Google Play Store™ page in Chrome Store.

#### Actual behavior
Open https://www.apkmirror.com/ page.

#### Steps to reproduce the problem
Select the first item in context menu of extension Toolbox for Google Play Store™ icon.

**Comment by corbindavenport** [comment]
I believe this happens due to APKMirror being set as the developer site. I'll look and see if this can be changed.

**Comment by archon810** [comment]
I see some extensions customize it to go to a dedicated page, which we don't really have. I'm OK with it linking to the extension page.

**Comment by archon810** [comment]
Fixed in 1.0.11.
